config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  mount Sidekiq::Web => "/sidekiq"

  resources :collections, except: %i[destroy] do
    resources :images, shallow: true
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/collection.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: collections
#
#  id          :uuid             not null, primary key
#  description :text
#  name        :string
#  slug        :string           not null
#  url         :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_collections_on_slug  (slug) UNIQUE
#

class Collection < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :images, dependent: :destroy

  validates :url, url: { allow_blank: true }
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id            :uuid             not null, primary key
#  http_status   :integer          default("unknown"), not null
#  pinged_at     :datetime
#  url           :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  collection_id :bigint           not null
#
# Indexes
#
#  index_images_on_collection_id  (collection_id)
#  uniq_rails_0b1e038289          (url) UNIQUE
#
class Image < ApplicationRecord
  belongs_to :collection

  enum http_status: {
      unknown: 0,
      **Rack::Utils::SYMBOL_TO_STATUS_CODE
    }, _prefix: true

  validates :url, url: { no_local: true }

  after_save :ping

  scope :latest, -> { order(created_at: :desc) }

  protected

  def ping
    ImagePingerJob.perform_async id if url_previously_changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: %i[ show edit update destroy ]

  # GET /collections
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  def create
    @collection = Collection.new(collection_params)

    if @collection.save
      redirect_to @collection, notice: "Collection was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /collections/1
  def update
    if @collection.update(collection_params)
      redirect_to @collection, notice: "Collection was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /collections/1
  def destroy
    @collection.destroy!
    redirect_to collections_url, notice: "Collection was successfully destroyed.", status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_collection
    @collection = Collection.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def collection_params
    params.require(:collection).permit(:name, :url, :description)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_collection, only: %i[index new create]
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images
  def index
    @images = @collection.images.all
  end

  # GET /images/1
  def show
  end

  # GET /images/new
  def new
    @image = @collection.images.build
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  def create
    @image = Image.new(image_params)
    @image.collection = @collection

    if @image.save
      redirect_to @image, notice: "Image was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /images/1
  def update
    if @image.update(image_params)
      redirect_to @image, notice: "Image was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /images/1
  def destroy
    @image.destroy!
    redirect_to images_url, notice: "Image was successfully destroyed.", status: :see_other
  end

  private
  def set_collection
    @collection = Collection.friendly.find(params[:collection_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = Image.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def image_params
    params.require(:image).permit(:url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/collections/_collection.html.erb
<div id="<%= dom_id collection %>" class="border p-4 m-2 border-gray-200 flex flex-col rounded"
>
  <div class="flex justify-between mb-4 items-center">
    <a href="<%= collection_path(collection) %>">
      <span class="font-xl font-medium">
        <%= collection.name %>
      </span>
    </a>

    <% if collection.url.present? %>
      <a href="<%= collection.url %>" class="bg-blue-50 border rounded px-3 py-1 hover:shadow">
        <span class="text-sm">
          Source
        </span>
      </a>
    <% end %>
  </div>

  <p class="text-sm text-gray-800">
    <%= collection.description %>
  </p>

</div>

app/views/collections/_form.html.erb
<%= form_with(model: collection, class: "contents") do |form| %>
  <% if collection.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% collection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :url %>
    <%= form.text_field :url, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing collection</h1>

  <%= render "form", collection: @collection %>

  <%= link_to "Show this collection", @collection, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to collections", collections_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/collections/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Collections" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Collections</h1>
    <%= link_to "New collection", new_collection_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="collections" class="min-w-full flex flex-col">
    <% @collections.each do |collection| %>
      <%= render collection %>
    <% end %>
  </div>
</div>

app/views/collections/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New collection</h1>

  <%= render "form", collection: @collection %>

  <%= link_to "Back to collections", collections_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/collections/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @collection %>

    <div class="w-full flex justify-between">
      <%= link_to "View Images", collection_images_path(@collection),
                  class: "rounded-lg py-3 px-5 bg-blue-100 inline-block font-medium" %>

      <%= link_to "Edit this collection", edit_collection_path(@collection),
                  class: "rounded-lg py-3 px-5 bg-green-100 inline-block font-medium" %>
      <%= link_to "Back to collections", collections_path,
                  class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="m-auto">
  <span class="text-lg">
    Welcome to
  </span>
  <h3 class="font-bold text-2xl">
    OpenDiffusion Dataset
  </h3>
</div>

app/views/images/_form.html.erb
<%= form_with(model: [collection, image], class: "contents") do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :url %>
    <%= form.text_field :url, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/images/_image.html.erb
<div id="<%= dom_id image %>">
  <img src="<%= image.url %>">
</div>

app/views/images/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing image</h1>

  <%= render "form", image: @image %>

  <%= link_to "Show this image", @image, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to images", images_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/images/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Images" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= @collection.name %> images</h1>
    <%= link_to "New image", new_collection_image_path(@collection),
                class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="images" class="min-w-full grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-2 mt-4">
    <% @images.each do |image| %>
      <div id="<%= dom_id image %>" class="rounded hover:shadow">
        <a href="<%= image_path(image) %>">
          <img src="<%= image.url %>" class="rounded">
        </a>
      </div>

      <!-- <p>
           <%= link_to "Show this image", image, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
           </p> -->
    <% end %>
  </div>
</div>

app/views/images/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New image</h1>

  <%= render "form", collection: @collection, image: @image %>

  <%= link_to "Back to images", collection_images_path(@collection),
              class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/images/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @image %>

    <%= link_to "Edit this image", edit_image_path(@image),
                class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to images", collection_images_path(@image.collection_id),
                class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this image", @image, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="border-gray-200 bg-white dark:bg-gray-900 border-b border-gray-300">
  <div class="mx-auto flex flex-wrap items-center justify-between p-4">
    <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
      <span
        class="self-center whitespace-nowrap text-2xl font-semibold dark:text-white"
      >φ Dataset</span
                >
    </a>
    <button
      data-collapse-toggle="navbar-default"
      type="button"
      class="inline-flex h-10 w-10 items-center justify-center rounded-lg p-2 text-sm text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600 md:hidden"
      aria-controls="navbar-default"
      aria-expanded="false"
    >
      <span class="sr-only">Open main menu</span>
      <svg
        class="h-5 w-5"
        aria-hidden="true"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 17 14"
      >
        <path
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M1 1h15M1 7h15M1 13h15"
        />
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul
        class="mt-4 flex flex-col rounded-lg border border-gray-100 bg-gray-50 p-4 font-medium rtl:space-x-reverse dark:border-gray-700 dark:bg-gray-800 md:mt-0 md:flex-row md:space-x-8 md:border-0 md:bg-white md:p-0 md:dark:bg-gray-900"
      >
        <li>
          <a
            href="<%= collections_path %>"
            class="block rounded bg-blue-700 py-2 px-3 text-white dark:text-white md:bg-transparent md:p-0 md:text-blue-700 md:dark:text-blue-500"
            aria-current="page"
            >Datasets</a
          >
        </li>
        <li>
          <a
            href="#"
            class="block rounded py-2 px-3 text-gray-900 hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:border-0 md:p-0 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:bg-transparent md:dark:hover:text-blue-500"
            >Submit</a
          >
        </li>
        <li>
          <a
            href="#"
            class="block rounded py-2 px-3 text-gray-900 hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:border-0 md:p-0 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:bg-transparent md:dark:hover:text-blue-500"
            >Tag</a
          >
        </li>
        <li>
          <a
            href="#"
            class="block rounded py-2 px-3 text-gray-900 hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:border-0 md:p-0 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:bg-transparent md:dark:hover:text-blue-500"
            >Review</a
          >
        </li>
        <li>
          <a
            href="#"
            class="block rounded py-2 px-3 text-gray-900 hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:border-0 md:p-0 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:bg-transparent md:dark:hover:text-blue-500"
            >Help</a
          >
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>φ Dataset</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex min-h-full flex-col">
    <main class="container mx-auto px-5 flex flex-col grow">
      <%= render partial: 'layouts/navbar' %>

      <div class="p-4 pt-8 grow flex flex-col">
        <%= yield %>
      </div>
    </main>
  </body>
</html>